# Generated by Django 4.2.20 on 2025-03-12 13:48

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=1000, null=True))),
                ('api_secret', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=1000, null=True))),
                ('access_token', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=1000, null=True))),
                ('access_secret', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=1000, null=True))),
                ('bearer_token', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=1000, null=True))),
            ],
        ),
    ]
